### ISSUE TITLE
I might have screwed up this repository.

### ISSUE THREAD

**Issue by toropov023** [RaiderRobotics/Herbert-IT#1]
This repository might have to be deleted and created again...

**Comment by sirsavary** [comment]
What's wrong with it?

**Comment by toropov023** [comment]
Accidentally made a force push on the master branch instead of the other one. We have a local copy of   the current commit and, I believe, a local copy of the original master somewhere around (might have to be clarified with @salamander2).

**Comment by sirsavary** [comment]
NEVER FORCE PUSH

This is fixable though. You should be able to either force push the local repository as it is now, or perform something similar to a rebase. I should be back in action tomorrow, I'll see if I can help.

**Comment by salamander2** [comment]
It has been fixed. The Toropov023 branch is still unchanged.
