### ISSUE TITLE
Gyro coding questions

### ISSUE THREAD

**Issue by salamander2** [RaiderRobotics/Herbert-IT#3]
Hey Kirill,

I'm wondering, (1) why did you make a separate package for the sensors, rather than just making them separate files in the same class as the main program Robot.java?

(2) I'm also wondering about the constructor.  I guess you do need to get the drivetrain and joystick sent to the quickturn class so that it can monitor them.

**Comment by toropov023** [comment]
It's a good habit storing classes that share some common functionality in a separate package. Also, it helps to organize the project to avoid the unnecessary mess.
